// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rpc.proto

/*
Package rpcpb is a generated protocol buffer package.

It is generated from these files:
	rpc.proto

It has these top-level messages:
	GetAccountStateRequest
	GetAccountStateResponse
	GetBlockRequest
	GetBlockResponse
	NonParamsRequest
	GetMedStateResponse
	TransactionData
	TransactionRequest
	TransactionResponse
*/
package rpcpb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import corepb "github.com/medibloc/go-medibloc/core/pb"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type GetAccountStateRequest struct {
	// Hex string of the account addresss.
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// block account state with height. If not specified, use 0 as tail height.
	Height uint64 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
}

func (m *GetAccountStateRequest) Reset()                    { *m = GetAccountStateRequest{} }
func (m *GetAccountStateRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAccountStateRequest) ProtoMessage()               {}
func (*GetAccountStateRequest) Descriptor() ([]byte, []int) { return fileDescriptorRpc, []int{0} }

func (m *GetAccountStateRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *GetAccountStateRequest) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type GetAccountStateResponse struct {
	// Current balance in unit of 1/(10^18) nas.
	Balance string `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	// Current transaction count.
	Nonce uint64 `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Account type
	Type uint32 `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
}

func (m *GetAccountStateResponse) Reset()                    { *m = GetAccountStateResponse{} }
func (m *GetAccountStateResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAccountStateResponse) ProtoMessage()               {}
func (*GetAccountStateResponse) Descriptor() ([]byte, []int) { return fileDescriptorRpc, []int{1} }

func (m *GetAccountStateResponse) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *GetAccountStateResponse) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *GetAccountStateResponse) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

type GetBlockRequest struct {
	// Block hash
	Hash string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *GetBlockRequest) Reset()                    { *m = GetBlockRequest{} }
func (m *GetBlockRequest) String() string            { return proto.CompactTextString(m) }
func (*GetBlockRequest) ProtoMessage()               {}
func (*GetBlockRequest) Descriptor() ([]byte, []int) { return fileDescriptorRpc, []int{2} }

func (m *GetBlockRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type GetBlockResponse struct {
	// Block
	Block *corepb.Block `protobuf:"bytes,1,opt,name=block" json:"block,omitempty"`
}

func (m *GetBlockResponse) Reset()                    { *m = GetBlockResponse{} }
func (m *GetBlockResponse) String() string            { return proto.CompactTextString(m) }
func (*GetBlockResponse) ProtoMessage()               {}
func (*GetBlockResponse) Descriptor() ([]byte, []int) { return fileDescriptorRpc, []int{3} }

func (m *GetBlockResponse) GetBlock() *corepb.Block {
	if m != nil {
		return m.Block
	}
	return nil
}

type NonParamsRequest struct {
}

func (m *NonParamsRequest) Reset()                    { *m = NonParamsRequest{} }
func (m *NonParamsRequest) String() string            { return proto.CompactTextString(m) }
func (*NonParamsRequest) ProtoMessage()               {}
func (*NonParamsRequest) Descriptor() ([]byte, []int) { return fileDescriptorRpc, []int{4} }

type GetMedStateResponse struct {
	// Block chain id
	ChainId uint32 `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	// Current tail block hash
	Tail string `protobuf:"bytes,2,opt,name=tail,proto3" json:"tail,omitempty"`
	// Current tail block height
	Height uint64 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	// The current med protocol version.
	ProtocolVersion string `protobuf:"bytes,7,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// Med version
	Version string `protobuf:"bytes,8,opt,name=version,proto3" json:"version,omitempty"`
}

func (m *GetMedStateResponse) Reset()                    { *m = GetMedStateResponse{} }
func (m *GetMedStateResponse) String() string            { return proto.CompactTextString(m) }
func (*GetMedStateResponse) ProtoMessage()               {}
func (*GetMedStateResponse) Descriptor() ([]byte, []int) { return fileDescriptorRpc, []int{5} }

func (m *GetMedStateResponse) GetChainId() uint32 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *GetMedStateResponse) GetTail() string {
	if m != nil {
		return m.Tail
	}
	return ""
}

func (m *GetMedStateResponse) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *GetMedStateResponse) GetProtocolVersion() string {
	if m != nil {
		return m.ProtocolVersion
	}
	return ""
}

func (m *GetMedStateResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type TransactionData struct {
	Type    string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload string `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *TransactionData) Reset()                    { *m = TransactionData{} }
func (m *TransactionData) String() string            { return proto.CompactTextString(m) }
func (*TransactionData) ProtoMessage()               {}
func (*TransactionData) Descriptor() ([]byte, []int) { return fileDescriptorRpc, []int{6} }

func (m *TransactionData) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *TransactionData) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type TransactionRequest struct {
	// Transaction hash
	Hash string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	// Hex string of the sender account addresss.
	From string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	// Hex string of the receiver account addresss.
	To string `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	// Amount of value sending with this transaction.
	Value string `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	// Transaction timestamp.
	Timestamp int64 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Transaction Data type.
	Data *TransactionData `protobuf:"bytes,6,opt,name=data" json:"data,omitempty"`
	// Transaction nonce.
	Nonce uint64 `protobuf:"varint,7,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Transaction chain ID.
	ChainId uint32 `protobuf:"varint,8,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	// Transaction algorithm.
	Alg uint32 `protobuf:"varint,9,opt,name=alg,proto3" json:"alg,omitempty"`
	// Transaction sign.
	Sign string `protobuf:"bytes,10,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (m *TransactionRequest) Reset()                    { *m = TransactionRequest{} }
func (m *TransactionRequest) String() string            { return proto.CompactTextString(m) }
func (*TransactionRequest) ProtoMessage()               {}
func (*TransactionRequest) Descriptor() ([]byte, []int) { return fileDescriptorRpc, []int{7} }

func (m *TransactionRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *TransactionRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *TransactionRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *TransactionRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *TransactionRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *TransactionRequest) GetData() *TransactionData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *TransactionRequest) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *TransactionRequest) GetChainId() uint32 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *TransactionRequest) GetAlg() uint32 {
	if m != nil {
		return m.Alg
	}
	return 0
}

func (m *TransactionRequest) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

type TransactionResponse struct {
	// Hex string of transaction hash.
	Txhash string `protobuf:"bytes,1,opt,name=txhash,proto3" json:"txhash,omitempty"`
}

func (m *TransactionResponse) Reset()                    { *m = TransactionResponse{} }
func (m *TransactionResponse) String() string            { return proto.CompactTextString(m) }
func (*TransactionResponse) ProtoMessage()               {}
func (*TransactionResponse) Descriptor() ([]byte, []int) { return fileDescriptorRpc, []int{8} }

func (m *TransactionResponse) GetTxhash() string {
	if m != nil {
		return m.Txhash
	}
	return ""
}

func init() {
	proto.RegisterType((*GetAccountStateRequest)(nil), "rpcpb.GetAccountStateRequest")
	proto.RegisterType((*GetAccountStateResponse)(nil), "rpcpb.GetAccountStateResponse")
	proto.RegisterType((*GetBlockRequest)(nil), "rpcpb.GetBlockRequest")
	proto.RegisterType((*GetBlockResponse)(nil), "rpcpb.GetBlockResponse")
	proto.RegisterType((*NonParamsRequest)(nil), "rpcpb.NonParamsRequest")
	proto.RegisterType((*GetMedStateResponse)(nil), "rpcpb.GetMedStateResponse")
	proto.RegisterType((*TransactionData)(nil), "rpcpb.TransactionData")
	proto.RegisterType((*TransactionRequest)(nil), "rpcpb.TransactionRequest")
	proto.RegisterType((*TransactionResponse)(nil), "rpcpb.TransactionResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ApiService service

type ApiServiceClient interface {
	GetAccountState(ctx context.Context, in *GetAccountStateRequest, opts ...grpc.CallOption) (*GetAccountStateResponse, error)
	GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*GetBlockResponse, error)
	GetMedState(ctx context.Context, in *NonParamsRequest, opts ...grpc.CallOption) (*GetMedStateResponse, error)
	GetTailBlock(ctx context.Context, in *NonParamsRequest, opts ...grpc.CallOption) (*GetBlockResponse, error)
	PostTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error)
}

type apiServiceClient struct {
	cc *grpc.ClientConn
}

func NewApiServiceClient(cc *grpc.ClientConn) ApiServiceClient {
	return &apiServiceClient{cc}
}

func (c *apiServiceClient) GetAccountState(ctx context.Context, in *GetAccountStateRequest, opts ...grpc.CallOption) (*GetAccountStateResponse, error) {
	out := new(GetAccountStateResponse)
	err := grpc.Invoke(ctx, "/rpcpb.ApiService/GetAccountState", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*GetBlockResponse, error) {
	out := new(GetBlockResponse)
	err := grpc.Invoke(ctx, "/rpcpb.ApiService/GetBlock", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) GetMedState(ctx context.Context, in *NonParamsRequest, opts ...grpc.CallOption) (*GetMedStateResponse, error) {
	out := new(GetMedStateResponse)
	err := grpc.Invoke(ctx, "/rpcpb.ApiService/GetMedState", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) GetTailBlock(ctx context.Context, in *NonParamsRequest, opts ...grpc.CallOption) (*GetBlockResponse, error) {
	out := new(GetBlockResponse)
	err := grpc.Invoke(ctx, "/rpcpb.ApiService/GetTailBlock", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) PostTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error) {
	out := new(TransactionResponse)
	err := grpc.Invoke(ctx, "/rpcpb.ApiService/PostTransaction", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ApiService service

type ApiServiceServer interface {
	GetAccountState(context.Context, *GetAccountStateRequest) (*GetAccountStateResponse, error)
	GetBlock(context.Context, *GetBlockRequest) (*GetBlockResponse, error)
	GetMedState(context.Context, *NonParamsRequest) (*GetMedStateResponse, error)
	GetTailBlock(context.Context, *NonParamsRequest) (*GetBlockResponse, error)
	PostTransaction(context.Context, *TransactionRequest) (*TransactionResponse, error)
}

func RegisterApiServiceServer(s *grpc.Server, srv ApiServiceServer) {
	s.RegisterService(&_ApiService_serviceDesc, srv)
}

func _ApiService_GetAccountState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).GetAccountState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.ApiService/GetAccountState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).GetAccountState(ctx, req.(*GetAccountStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_GetBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).GetBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.ApiService/GetBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).GetBlock(ctx, req.(*GetBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_GetMedState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NonParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).GetMedState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.ApiService/GetMedState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).GetMedState(ctx, req.(*NonParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_GetTailBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NonParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).GetTailBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.ApiService/GetTailBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).GetTailBlock(ctx, req.(*NonParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_PostTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).PostTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.ApiService/PostTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).PostTransaction(ctx, req.(*TransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ApiService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpcpb.ApiService",
	HandlerType: (*ApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccountState",
			Handler:    _ApiService_GetAccountState_Handler,
		},
		{
			MethodName: "GetBlock",
			Handler:    _ApiService_GetBlock_Handler,
		},
		{
			MethodName: "GetMedState",
			Handler:    _ApiService_GetMedState_Handler,
		},
		{
			MethodName: "GetTailBlock",
			Handler:    _ApiService_GetTailBlock_Handler,
		},
		{
			MethodName: "PostTransaction",
			Handler:    _ApiService_PostTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}

// Client API for AdminService service

type AdminServiceClient interface {
	SendTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error)
}

type adminServiceClient struct {
	cc *grpc.ClientConn
}

func NewAdminServiceClient(cc *grpc.ClientConn) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) SendTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error) {
	out := new(TransactionResponse)
	err := grpc.Invoke(ctx, "/rpcpb.AdminService/SendTransaction", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AdminService service

type AdminServiceServer interface {
	SendTransaction(context.Context, *TransactionRequest) (*TransactionResponse, error)
}

func RegisterAdminServiceServer(s *grpc.Server, srv AdminServiceServer) {
	s.RegisterService(&_AdminService_serviceDesc, srv)
}

func _AdminService_SendTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).SendTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.AdminService/SendTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).SendTransaction(ctx, req.(*TransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AdminService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpcpb.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendTransaction",
			Handler:    _AdminService_SendTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptorRpc) }

var fileDescriptorRpc = []byte{
	// 713 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xdd, 0x6e, 0xd3, 0x4a,
	0x10, 0x56, 0xfe, 0x93, 0xe9, 0x4f, 0xd2, 0x6d, 0x4f, 0xea, 0x5a, 0xed, 0x51, 0xe4, 0xa3, 0x23,
	0x85, 0x4a, 0x8d, 0x45, 0x7b, 0x81, 0xc4, 0x0d, 0x2a, 0x42, 0x8a, 0x40, 0xa2, 0xaa, 0xdc, 0x0a,
	0x71, 0x53, 0x55, 0x1b, 0x7b, 0x71, 0x16, 0x6c, 0xaf, 0xf1, 0x6e, 0x22, 0xca, 0x25, 0x3c, 0x02,
	0x4f, 0xc0, 0x33, 0xf1, 0x0a, 0x5c, 0xf2, 0x10, 0x68, 0x67, 0xed, 0xc4, 0x4d, 0x5b, 0xae, 0xb8,
	0x9b, 0x19, 0xcf, 0x7e, 0xf3, 0xf3, 0x7d, 0x63, 0xe8, 0x64, 0xa9, 0x3f, 0x4a, 0x33, 0xa1, 0x04,
	0x69, 0x64, 0xa9, 0x9f, 0x4e, 0xec, 0xfd, 0x50, 0x88, 0x30, 0x62, 0x2e, 0x4d, 0xb9, 0x4b, 0x93,
	0x44, 0x28, 0xaa, 0xb8, 0x48, 0xa4, 0x49, 0xb2, 0x4f, 0x42, 0xae, 0xa6, 0xb3, 0xc9, 0xc8, 0x17,
	0xb1, 0x1b, 0xb3, 0x80, 0x4f, 0x22, 0xe1, 0xbb, 0xa1, 0x38, 0x5a, 0xd8, 0xbe, 0xc8, 0x98, 0x9b,
	0x4e, 0x5c, 0xed, 0x7c, 0x30, 0x8f, 0x9c, 0x57, 0xd0, 0x1f, 0x33, 0x75, 0xea, 0xfb, 0x62, 0x96,
	0xa8, 0x0b, 0x45, 0x15, 0xf3, 0xd8, 0xc7, 0x19, 0x93, 0x8a, 0x58, 0xd0, 0xa2, 0x41, 0x90, 0x31,
	0x29, 0xad, 0xca, 0xa0, 0x32, 0xec, 0x78, 0x85, 0x4b, 0xfa, 0xd0, 0x9c, 0x32, 0x1e, 0x4e, 0x95,
	0x55, 0x1d, 0x54, 0x86, 0x75, 0x2f, 0xf7, 0x9c, 0x2b, 0xd8, 0xbd, 0x83, 0x25, 0x53, 0x91, 0x48,
	0xa6, 0xc1, 0x26, 0x34, 0xa2, 0x89, 0xcf, 0x0a, 0xb0, 0xdc, 0x25, 0x3b, 0xd0, 0x48, 0x84, 0x8e,
	0x1b, 0x2c, 0xe3, 0x10, 0x02, 0x75, 0x75, 0x93, 0x32, 0xab, 0x36, 0xa8, 0x0c, 0x37, 0x3c, 0xb4,
	0x9d, 0xff, 0xa1, 0x3b, 0x66, 0xea, 0xb9, 0x6e, 0xbe, 0xe8, 0x91, 0x40, 0x7d, 0x4a, 0xe5, 0x34,
	0xc7, 0x44, 0xdb, 0x79, 0x02, 0xbd, 0x65, 0x5a, 0x5e, 0xfe, 0x3f, 0x68, 0xe0, 0xd0, 0x98, 0xb8,
	0x76, 0xbc, 0x31, 0xd2, 0xab, 0x48, 0x27, 0x23, 0x93, 0x65, 0xbe, 0x39, 0x04, 0x7a, 0x67, 0x22,
	0x39, 0xa7, 0x19, 0x8d, 0x65, 0x5e, 0xc0, 0xf9, 0x5e, 0x81, 0xed, 0x31, 0x53, 0xaf, 0x59, 0x70,
	0x7b, 0x9e, 0x3d, 0x68, 0xfb, 0x53, 0xca, 0x93, 0x6b, 0x1e, 0x20, 0xe6, 0x86, 0xd7, 0x42, 0xff,
	0x65, 0x80, 0xad, 0x53, 0x1e, 0xe1, 0x3c, 0x1d, 0x0f, 0xed, 0xd2, 0xc6, 0x6a, 0xe5, 0x8d, 0x91,
	0x47, 0xd0, 0x43, 0x1a, 0x7c, 0x11, 0x5d, 0xcf, 0x59, 0x26, 0xb9, 0x48, 0xac, 0x16, 0xbe, 0xeb,
	0x16, 0xf1, 0x37, 0x26, 0xac, 0x37, 0x58, 0x64, 0xb4, 0xcd, 0x06, 0x73, 0xd7, 0x79, 0x06, 0xdd,
	0xcb, 0x8c, 0x26, 0x92, 0xfa, 0x5a, 0x0d, 0x2f, 0xa8, 0xa2, 0x8b, 0xf5, 0xe5, 0x7b, 0xd1, 0xb6,
	0x06, 0x48, 0xe9, 0x4d, 0x24, 0x68, 0x90, 0xb7, 0x56, 0xb8, 0xce, 0xd7, 0x2a, 0x90, 0x12, 0xc2,
	0x1f, 0x96, 0xab, 0x63, 0xef, 0x32, 0x11, 0x17, 0xc3, 0x69, 0x9b, 0x6c, 0x42, 0x55, 0x09, 0x1c,
	0xac, 0xe3, 0x55, 0x95, 0xd0, 0x8c, 0xce, 0x69, 0x34, 0x63, 0x56, 0x1d, 0x43, 0xc6, 0x21, 0xfb,
	0xd0, 0x51, 0x3c, 0x66, 0x52, 0xd1, 0x38, 0xb5, 0x1a, 0x83, 0xca, 0xb0, 0xe6, 0x2d, 0x03, 0xe4,
	0x10, 0xea, 0x01, 0x55, 0xd4, 0x6a, 0x22, 0x3f, 0xfd, 0x11, 0xea, 0x7d, 0xb4, 0x32, 0x96, 0x87,
	0x39, 0x4b, 0xc5, 0xb4, 0xca, 0x8a, 0x29, 0x33, 0xd2, 0xbe, 0xcd, 0x48, 0x0f, 0x6a, 0x34, 0x0a,
	0xad, 0x0e, 0x46, 0xb5, 0xa9, 0xc7, 0x90, 0x3c, 0x4c, 0x2c, 0x30, 0x63, 0x68, 0xdb, 0x39, 0x82,
	0xed, 0x5b, 0x4b, 0xc8, 0x99, 0xee, 0x43, 0x53, 0x7d, 0x2a, 0xed, 0x21, 0xf7, 0x8e, 0x7f, 0xd5,
	0x00, 0x4e, 0x53, 0x7e, 0xc1, 0xb2, 0x39, 0xf7, 0x19, 0x11, 0x28, 0xce, 0xb2, 0xf6, 0xc9, 0x41,
	0x3e, 0xc5, 0xfd, 0xf7, 0x65, 0xff, 0xfb, 0xd0, 0x67, 0x53, 0xd8, 0x39, 0xf8, 0xf2, 0xe3, 0xe7,
	0xb7, 0xea, 0x2e, 0xf9, 0xc7, 0x9d, 0x3f, 0x76, 0x67, 0x92, 0x65, 0x2e, 0x35, 0x69, 0x12, 0xd1,
	0xcf, 0xa0, 0x5d, 0xc8, 0x9c, 0xf4, 0x97, 0x50, 0xe5, 0xf3, 0xb0, 0x77, 0xef, 0xc4, 0x73, 0xec,
	0x2d, 0xc4, 0x5e, 0x23, 0x1d, 0x8d, 0x8d, 0xea, 0x27, 0x57, 0xb0, 0x56, 0x12, 0x3a, 0x29, 0x9e,
	0xae, 0x5e, 0x84, 0x6d, 0x2f, 0x31, 0x57, 0xaf, 0xc2, 0xd9, 0x43, 0xd8, 0x6d, 0xb2, 0xb5, 0x68,
	0x39, 0x66, 0x81, 0x69, 0xf7, 0x2d, 0xac, 0x8f, 0x99, 0xba, 0xa4, 0x3c, 0x32, 0x2d, 0x3f, 0x88,
	0xff, 0x60, 0xcf, 0x7d, 0x04, 0xef, 0x91, 0xcd, 0x45, 0xcf, 0x2e, 0xde, 0x56, 0x00, 0xdd, 0x73,
	0x21, 0x55, 0x89, 0x3b, 0xb2, 0x77, 0x57, 0x3f, 0xab, 0xed, 0xdf, 0x43, 0xb5, 0x63, 0x63, 0x85,
	0x1d, 0xa7, 0xab, 0x2b, 0xa8, 0x65, 0xc2, 0xd3, 0xca, 0xe1, 0xf1, 0x67, 0x58, 0x3f, 0x0d, 0x62,
	0x9e, 0x14, 0x7c, 0xbf, 0x87, 0xee, 0x05, 0x4b, 0x82, 0xbf, 0x50, 0x75, 0x80, 0x55, 0x6d, 0x07,
	0x79, 0xa6, 0xba, 0xc6, 0x4a, 0xed, 0x49, 0x13, 0xff, 0x05, 0x27, 0xbf, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x95, 0x86, 0x1a, 0x83, 0x11, 0x06, 0x00, 0x00,
}
