// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

/*
Package rpcpb is a generated protocol buffer package.

It is generated from these files:
	rpc.proto

It has these top-level messages:
	GetAccountStateRequest
	GetAccountStateResponse
	TransactionRequest
	TransactionResponse
*/
package rpcpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetAccountStateRequest struct {
	// Hex string of the account addresss.
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	// block account state with height. If not specified, use 0 as tail height.
	Height uint64 `protobuf:"varint,2,opt,name=height" json:"height,omitempty"`
}

func (m *GetAccountStateRequest) Reset()                    { *m = GetAccountStateRequest{} }
func (m *GetAccountStateRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAccountStateRequest) ProtoMessage()               {}
func (*GetAccountStateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetAccountStateRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *GetAccountStateRequest) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type GetAccountStateResponse struct {
	// Current balance in unit of 1/(10^18) nas.
	Balance float32 `protobuf:"fixed32,1,opt,name=balance" json:"balance,omitempty"`
	// Current transaction count.
	Nonce uint64 `protobuf:"varint,2,opt,name=nonce" json:"nonce,omitempty"`
	// Account type
	Type uint32 `protobuf:"varint,3,opt,name=type" json:"type,omitempty"`
}

func (m *GetAccountStateResponse) Reset()                    { *m = GetAccountStateResponse{} }
func (m *GetAccountStateResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAccountStateResponse) ProtoMessage()               {}
func (*GetAccountStateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetAccountStateResponse) GetBalance() float32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *GetAccountStateResponse) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *GetAccountStateResponse) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

type TransactionRequest struct {
	// Hex string of the sender account addresss.
	From string `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	// Hex string of the receiver account addresss.
	To string `protobuf:"bytes,2,opt,name=to" json:"to,omitempty"`
	// Amount of value sending with this transaction.
	Value string `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
	// Transaction nonce.
	Nonce uint64 `protobuf:"varint,4,opt,name=nonce" json:"nonce,omitempty"`
}

func (m *TransactionRequest) Reset()                    { *m = TransactionRequest{} }
func (m *TransactionRequest) String() string            { return proto.CompactTextString(m) }
func (*TransactionRequest) ProtoMessage()               {}
func (*TransactionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TransactionRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *TransactionRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *TransactionRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *TransactionRequest) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

type TransactionResponse struct {
	// Hex string of transaction hash.
	Txhash string `protobuf:"bytes,1,opt,name=txhash" json:"txhash,omitempty"`
}

func (m *TransactionResponse) Reset()                    { *m = TransactionResponse{} }
func (m *TransactionResponse) String() string            { return proto.CompactTextString(m) }
func (*TransactionResponse) ProtoMessage()               {}
func (*TransactionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TransactionResponse) GetTxhash() string {
	if m != nil {
		return m.Txhash
	}
	return ""
}

func init() {
	proto.RegisterType((*GetAccountStateRequest)(nil), "rpcpb.GetAccountStateRequest")
	proto.RegisterType((*GetAccountStateResponse)(nil), "rpcpb.GetAccountStateResponse")
	proto.RegisterType((*TransactionRequest)(nil), "rpcpb.TransactionRequest")
	proto.RegisterType((*TransactionResponse)(nil), "rpcpb.TransactionResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ApiService service

type ApiServiceClient interface {
	GetAccountState(ctx context.Context, in *GetAccountStateRequest, opts ...grpc.CallOption) (*GetAccountStateResponse, error)
}

type apiServiceClient struct {
	cc *grpc.ClientConn
}

func NewApiServiceClient(cc *grpc.ClientConn) ApiServiceClient {
	return &apiServiceClient{cc}
}

func (c *apiServiceClient) GetAccountState(ctx context.Context, in *GetAccountStateRequest, opts ...grpc.CallOption) (*GetAccountStateResponse, error) {
	out := new(GetAccountStateResponse)
	err := grpc.Invoke(ctx, "/rpcpb.ApiService/GetAccountState", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ApiService service

type ApiServiceServer interface {
	GetAccountState(context.Context, *GetAccountStateRequest) (*GetAccountStateResponse, error)
}

func RegisterApiServiceServer(s *grpc.Server, srv ApiServiceServer) {
	s.RegisterService(&_ApiService_serviceDesc, srv)
}

func _ApiService_GetAccountState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).GetAccountState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.ApiService/GetAccountState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).GetAccountState(ctx, req.(*GetAccountStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ApiService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpcpb.ApiService",
	HandlerType: (*ApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccountState",
			Handler:    _ApiService_GetAccountState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}

// Client API for AdminService service

type AdminServiceClient interface {
	SendTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error)
}

type adminServiceClient struct {
	cc *grpc.ClientConn
}

func NewAdminServiceClient(cc *grpc.ClientConn) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) SendTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error) {
	out := new(TransactionResponse)
	err := grpc.Invoke(ctx, "/rpcpb.AdminService/SendTransaction", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AdminService service

type AdminServiceServer interface {
	SendTransaction(context.Context, *TransactionRequest) (*TransactionResponse, error)
}

func RegisterAdminServiceServer(s *grpc.Server, srv AdminServiceServer) {
	s.RegisterService(&_AdminService_serviceDesc, srv)
}

func _AdminService_SendTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).SendTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.AdminService/SendTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).SendTransaction(ctx, req.(*TransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AdminService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpcpb.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendTransaction",
			Handler:    _AdminService_SendTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 359 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xbf, 0x4e, 0xe3, 0x40,
	0x10, 0xc6, 0x65, 0x9f, 0x93, 0x93, 0x47, 0x77, 0x17, 0x69, 0x0f, 0x82, 0xb1, 0x00, 0x59, 0xae,
	0xa2, 0x48, 0xc4, 0x22, 0x74, 0xe9, 0x52, 0x21, 0x51, 0x3a, 0xb4, 0x14, 0x1b, 0x7b, 0x88, 0x8d,
	0x92, 0xdd, 0x65, 0x77, 0x1c, 0x01, 0x15, 0xe2, 0x15, 0x78, 0x34, 0x5e, 0x81, 0x07, 0x41, 0xfe,
	0xa7, 0x04, 0x12, 0xba, 0xf9, 0x3c, 0x9f, 0xbe, 0xdf, 0xcc, 0x78, 0xc1, 0xd5, 0x2a, 0x19, 0x29,
	0x2d, 0x49, 0xb2, 0x8e, 0x56, 0x89, 0x9a, 0xfb, 0x27, 0x0b, 0x29, 0x17, 0x4b, 0x8c, 0xb8, 0xca,
	0x23, 0x2e, 0x84, 0x24, 0x4e, 0xb9, 0x14, 0xa6, 0x36, 0x85, 0xd7, 0xd0, 0xbf, 0x42, 0x9a, 0x26,
	0x89, 0x2c, 0x04, 0xcd, 0x88, 0x13, 0xc6, 0xf8, 0x50, 0xa0, 0x21, 0xe6, 0xc1, 0x6f, 0x9e, 0xa6,
	0x1a, 0x8d, 0xf1, 0xac, 0xc0, 0x1a, 0xb8, 0x71, 0x2b, 0x59, 0x1f, 0xba, 0x19, 0xe6, 0x8b, 0x8c,
	0x3c, 0x3b, 0xb0, 0x06, 0x4e, 0xdc, 0xa8, 0xf0, 0x16, 0x8e, 0x76, 0xb2, 0x8c, 0x92, 0xc2, 0x60,
	0x19, 0x36, 0xe7, 0x4b, 0x2e, 0x12, 0xac, 0xc2, 0xec, 0xb8, 0x95, 0xec, 0x00, 0x3a, 0x42, 0x96,
	0xdf, 0xeb, 0xac, 0x5a, 0x30, 0x06, 0x0e, 0x3d, 0x29, 0xf4, 0x7e, 0x05, 0xd6, 0xe0, 0x6f, 0x5c,
	0xd5, 0x61, 0x0a, 0xec, 0x46, 0x73, 0x61, 0x78, 0x52, 0x2e, 0xd0, 0x8e, 0xc9, 0xc0, 0xb9, 0xd3,
	0x72, 0xd5, 0xcc, 0x58, 0xd5, 0xec, 0x1f, 0xd8, 0x24, 0xab, 0x40, 0x37, 0xb6, 0x49, 0x96, 0x8c,
	0x35, 0x5f, 0x16, 0x75, 0x9c, 0x1b, 0xd7, 0x62, 0x43, 0x76, 0xb6, 0xc8, 0xe1, 0x39, 0xfc, 0xff,
	0x42, 0x69, 0x16, 0xe8, 0x43, 0x97, 0x1e, 0x33, 0x6e, 0xb2, 0x06, 0xd4, 0xa8, 0xf1, 0x8b, 0x05,
	0x30, 0x55, 0xf9, 0x0c, 0xf5, 0x3a, 0x4f, 0x90, 0x69, 0xe8, 0x7d, 0x3b, 0x01, 0x3b, 0x1d, 0x55,
	0xff, 0x61, 0xb4, 0xff, 0xcc, 0xfe, 0xd9, 0x4f, 0xed, 0x1a, 0x1c, 0x06, 0xaf, 0xef, 0x1f, 0x6f,
	0xb6, 0x1f, 0x1e, 0x46, 0xeb, 0x8b, 0xa8, 0x30, 0xa8, 0x23, 0x5e, 0xdb, 0x4c, 0x69, 0x9b, 0x58,
	0xc3, 0xf1, 0x33, 0xfc, 0x99, 0xa6, 0xab, 0x5c, 0xb4, 0x33, 0xdc, 0x43, 0x6f, 0x86, 0x22, 0xdd,
	0xda, 0x82, 0x1d, 0x37, 0x90, 0xdd, 0xfb, 0xf9, 0xfe, 0xbe, 0xd6, 0x3e, 0x36, 0x2f, 0x19, 0x11,
	0x6d, 0x6c, 0x13, 0x6b, 0x38, 0xef, 0x56, 0xaf, 0xe8, 0xf2, 0x33, 0x00, 0x00, 0xff, 0xff, 0x2c,
	0xfc, 0x96, 0xf0, 0x77, 0x02, 0x00, 0x00,
}
