// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: account.proto

/*
Package corepb is a generated protocol buffer package.

It is generated from these files:
	account.proto

It has these top-level messages:
	Account
*/
package corepb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Account struct {
	Address       []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Balance       []byte   `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Nonce         uint64   `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Vesting       []byte   `protobuf:"bytes,4,opt,name=vesting,proto3" json:"vesting,omitempty"`
	Voted         []byte   `protobuf:"bytes,5,opt,name=voted,proto3" json:"voted,omitempty"`
	Records       [][]byte `protobuf:"bytes,6,rep,name=records" json:"records,omitempty"`
	CertsReceived [][]byte `protobuf:"bytes,7,rep,name=certs_received,json=certsReceived" json:"certs_received,omitempty"`
	CertsIssued   [][]byte `protobuf:"bytes,8,rep,name=certs_issued,json=certsIssued" json:"certs_issued,omitempty"`
	// Transactions
	TxsFrom [][]byte `protobuf:"bytes,9,rep,name=txs_from,json=txsFrom" json:"txs_from,omitempty"`
	TxsTo   [][]byte `protobuf:"bytes,10,rep,name=txs_to,json=txsTo" json:"txs_to,omitempty"`
}

func (m *Account) Reset()                    { *m = Account{} }
func (m *Account) String() string            { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()               {}
func (*Account) Descriptor() ([]byte, []int) { return fileDescriptorAccount, []int{0} }

func (m *Account) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Account) GetBalance() []byte {
	if m != nil {
		return m.Balance
	}
	return nil
}

func (m *Account) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Account) GetVesting() []byte {
	if m != nil {
		return m.Vesting
	}
	return nil
}

func (m *Account) GetVoted() []byte {
	if m != nil {
		return m.Voted
	}
	return nil
}

func (m *Account) GetRecords() [][]byte {
	if m != nil {
		return m.Records
	}
	return nil
}

func (m *Account) GetCertsReceived() [][]byte {
	if m != nil {
		return m.CertsReceived
	}
	return nil
}

func (m *Account) GetCertsIssued() [][]byte {
	if m != nil {
		return m.CertsIssued
	}
	return nil
}

func (m *Account) GetTxsFrom() [][]byte {
	if m != nil {
		return m.TxsFrom
	}
	return nil
}

func (m *Account) GetTxsTo() [][]byte {
	if m != nil {
		return m.TxsTo
	}
	return nil
}

func init() {
	proto.RegisterType((*Account)(nil), "corepb.Account")
}

func init() { proto.RegisterFile("account.proto", fileDescriptorAccount) }

var fileDescriptorAccount = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x49, 0xdb, 0x24, 0x75, 0x6c, 0x3d, 0x2c, 0x0a, 0xe3, 0x2d, 0x0a, 0x42, 0x4f, 0x5e,
	0x7c, 0x02, 0x2f, 0x82, 0xd7, 0xe0, 0xbd, 0x24, 0xbb, 0xa3, 0x04, 0x6c, 0xa6, 0xcc, 0x4c, 0x43,
	0x5e, 0xc5, 0xb7, 0x95, 0xdd, 0x4d, 0x8f, 0xdf, 0xf7, 0x7f, 0x30, 0x30, 0xb0, 0xef, 0xbc, 0xe7,
	0xcb, 0x68, 0xaf, 0x67, 0x61, 0x63, 0x57, 0x79, 0x16, 0x3a, 0xf7, 0xcf, 0x7f, 0x2b, 0xa8, 0xdf,
	0xf3, 0xe2, 0x10, 0xea, 0x2e, 0x04, 0x21, 0x55, 0x2c, 0x9a, 0xe2, 0xb0, 0x6b, 0xaf, 0x18, 0x97,
	0xbe, 0xfb, 0xed, 0x46, 0x4f, 0xb8, 0xca, 0xcb, 0x82, 0xee, 0x1e, 0xca, 0x91, 0xa3, 0x5f, 0x37,
	0xc5, 0x61, 0xd3, 0x66, 0x88, 0xfd, 0x44, 0x6a, 0xc3, 0xf8, 0x83, 0x9b, 0xdc, 0x2f, 0x18, 0xfb,
	0x89, 0x8d, 0x02, 0x96, 0xc9, 0x67, 0x88, 0xbd, 0x90, 0x67, 0x09, 0x8a, 0x55, 0xb3, 0x8e, 0xfd,
	0x82, 0xee, 0x05, 0xee, 0x3c, 0x89, 0xe9, 0x51, 0xc8, 0xd3, 0x30, 0x51, 0xc0, 0x3a, 0x05, 0xfb,
	0x64, 0xdb, 0x45, 0xba, 0x27, 0xd8, 0xe5, 0x6c, 0x50, 0xbd, 0x50, 0xc0, 0x6d, 0x8a, 0x6e, 0x93,
	0xfb, 0x4c, 0xca, 0x3d, 0xc2, 0xd6, 0x66, 0x3d, 0x7e, 0x0b, 0x9f, 0xf0, 0x26, 0x1f, 0xb1, 0x59,
	0x3f, 0x84, 0x4f, 0xee, 0x01, 0xaa, 0x38, 0x19, 0x23, 0xa4, 0xa1, 0xb4, 0x59, 0xbf, 0xb8, 0xaf,
	0xd2, 0xab, 0xde, 0xfe, 0x03, 0x00, 0x00, 0xff, 0xff, 0xa0, 0x7f, 0x68, 0x17, 0x3b, 0x01, 0x00,
	0x00,
}
