// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: block.proto

/*
Package corepb is a generated protocol buffer package.

It is generated from these files:
	block.proto

It has these top-level messages:
	BlockHeader
	Block
	DownloadParentBlock
	BlockHashTarget
	Transaction
	Receipt
	TransactionHashTarget
	DefaultPayload
	VotePayload
	AddCertificationPayload
	RevokeCertificationPayload
	AddRecordPayload
	RegisterAliasPayload
*/
package corepb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type BlockHeader struct {
	Hash         []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	ParentHash   []byte `protobuf:"bytes,2,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	Coinbase     []byte `protobuf:"bytes,3,opt,name=coinbase,proto3" json:"coinbase,omitempty"`
	Reward       []byte `protobuf:"bytes,4,opt,name=reward,proto3" json:"reward,omitempty"`
	Supply       []byte `protobuf:"bytes,5,opt,name=supply,proto3" json:"supply,omitempty"`
	Timestamp    int64  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ChainId      uint32 `protobuf:"varint,7,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Alg          uint32 `protobuf:"varint,11,opt,name=alg,proto3" json:"alg,omitempty"`
	Sign         []byte `protobuf:"bytes,12,opt,name=sign,proto3" json:"sign,omitempty"`
	AccStateRoot []byte `protobuf:"bytes,21,opt,name=acc_state_root,json=accStateRoot,proto3" json:"acc_state_root,omitempty"`
	TxStateRoot  []byte `protobuf:"bytes,22,opt,name=tx_state_root,json=txStateRoot,proto3" json:"tx_state_root,omitempty"`
	DposRoot     []byte `protobuf:"bytes,23,opt,name=dpos_root,json=dposRoot,proto3" json:"dpos_root,omitempty"`
	CpuRef       []byte `protobuf:"bytes,30,opt,name=cpu_ref,json=cpuRef,proto3" json:"cpu_ref,omitempty"`
	CpuUsage     []byte `protobuf:"bytes,31,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	NetRef       []byte `protobuf:"bytes,32,opt,name=net_ref,json=netRef,proto3" json:"net_ref,omitempty"`
	NetUsage     []byte `protobuf:"bytes,33,opt,name=net_usage,json=netUsage,proto3" json:"net_usage,omitempty"`
}

func (m *BlockHeader) Reset()                    { *m = BlockHeader{} }
func (m *BlockHeader) String() string            { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()               {}
func (*BlockHeader) Descriptor() ([]byte, []int) { return fileDescriptorBlock, []int{0} }

func (m *BlockHeader) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *BlockHeader) GetParentHash() []byte {
	if m != nil {
		return m.ParentHash
	}
	return nil
}

func (m *BlockHeader) GetCoinbase() []byte {
	if m != nil {
		return m.Coinbase
	}
	return nil
}

func (m *BlockHeader) GetReward() []byte {
	if m != nil {
		return m.Reward
	}
	return nil
}

func (m *BlockHeader) GetSupply() []byte {
	if m != nil {
		return m.Supply
	}
	return nil
}

func (m *BlockHeader) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *BlockHeader) GetChainId() uint32 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *BlockHeader) GetAlg() uint32 {
	if m != nil {
		return m.Alg
	}
	return 0
}

func (m *BlockHeader) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

func (m *BlockHeader) GetAccStateRoot() []byte {
	if m != nil {
		return m.AccStateRoot
	}
	return nil
}

func (m *BlockHeader) GetTxStateRoot() []byte {
	if m != nil {
		return m.TxStateRoot
	}
	return nil
}

func (m *BlockHeader) GetDposRoot() []byte {
	if m != nil {
		return m.DposRoot
	}
	return nil
}

func (m *BlockHeader) GetCpuRef() []byte {
	if m != nil {
		return m.CpuRef
	}
	return nil
}

func (m *BlockHeader) GetCpuUsage() []byte {
	if m != nil {
		return m.CpuUsage
	}
	return nil
}

func (m *BlockHeader) GetNetRef() []byte {
	if m != nil {
		return m.NetRef
	}
	return nil
}

func (m *BlockHeader) GetNetUsage() []byte {
	if m != nil {
		return m.NetUsage
	}
	return nil
}

type Block struct {
	Header       *BlockHeader   `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Transactions []*Transaction `protobuf:"bytes,2,rep,name=transactions" json:"transactions,omitempty"`
	Height       uint64         `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
}

func (m *Block) Reset()                    { *m = Block{} }
func (m *Block) String() string            { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()               {}
func (*Block) Descriptor() ([]byte, []int) { return fileDescriptorBlock, []int{1} }

func (m *Block) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *Block) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type DownloadParentBlock struct {
	Hash []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Sign []byte `protobuf:"bytes,2,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (m *DownloadParentBlock) Reset()                    { *m = DownloadParentBlock{} }
func (m *DownloadParentBlock) String() string            { return proto.CompactTextString(m) }
func (*DownloadParentBlock) ProtoMessage()               {}
func (*DownloadParentBlock) Descriptor() ([]byte, []int) { return fileDescriptorBlock, []int{2} }

func (m *DownloadParentBlock) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *DownloadParentBlock) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type BlockHashTarget struct {
	ParentHash   []byte   `protobuf:"bytes,1,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	Coinbase     []byte   `protobuf:"bytes,2,opt,name=coinbase,proto3" json:"coinbase,omitempty"`
	AccStateRoot []byte   `protobuf:"bytes,3,opt,name=acc_state_root,json=accStateRoot,proto3" json:"acc_state_root,omitempty"`
	TxStateRoot  []byte   `protobuf:"bytes,4,opt,name=tx_state_root,json=txStateRoot,proto3" json:"tx_state_root,omitempty"`
	DposRoot     []byte   `protobuf:"bytes,5,opt,name=dpos_root,json=dposRoot,proto3" json:"dpos_root,omitempty"`
	Timestamp    int64    `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ChainId      uint32   `protobuf:"varint,7,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Reward       []byte   `protobuf:"bytes,8,opt,name=reward,proto3" json:"reward,omitempty"`
	Supply       []byte   `protobuf:"bytes,9,opt,name=supply,proto3" json:"supply,omitempty"`
	CpuUsage     []byte   `protobuf:"bytes,20,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	NetUsage     []byte   `protobuf:"bytes,21,opt,name=net_usage,json=netUsage,proto3" json:"net_usage,omitempty"`
	TxHash       [][]byte `protobuf:"bytes,30,rep,name=tx_hash,json=txHash" json:"tx_hash,omitempty"`
}

func (m *BlockHashTarget) Reset()                    { *m = BlockHashTarget{} }
func (m *BlockHashTarget) String() string            { return proto.CompactTextString(m) }
func (*BlockHashTarget) ProtoMessage()               {}
func (*BlockHashTarget) Descriptor() ([]byte, []int) { return fileDescriptorBlock, []int{3} }

func (m *BlockHashTarget) GetParentHash() []byte {
	if m != nil {
		return m.ParentHash
	}
	return nil
}

func (m *BlockHashTarget) GetCoinbase() []byte {
	if m != nil {
		return m.Coinbase
	}
	return nil
}

func (m *BlockHashTarget) GetAccStateRoot() []byte {
	if m != nil {
		return m.AccStateRoot
	}
	return nil
}

func (m *BlockHashTarget) GetTxStateRoot() []byte {
	if m != nil {
		return m.TxStateRoot
	}
	return nil
}

func (m *BlockHashTarget) GetDposRoot() []byte {
	if m != nil {
		return m.DposRoot
	}
	return nil
}

func (m *BlockHashTarget) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *BlockHashTarget) GetChainId() uint32 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *BlockHashTarget) GetReward() []byte {
	if m != nil {
		return m.Reward
	}
	return nil
}

func (m *BlockHashTarget) GetSupply() []byte {
	if m != nil {
		return m.Supply
	}
	return nil
}

func (m *BlockHashTarget) GetCpuUsage() []byte {
	if m != nil {
		return m.CpuUsage
	}
	return nil
}

func (m *BlockHashTarget) GetNetUsage() []byte {
	if m != nil {
		return m.NetUsage
	}
	return nil
}

func (m *BlockHashTarget) GetTxHash() [][]byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

type Transaction struct {
	Hash      []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	TxType    string   `protobuf:"bytes,2,opt,name=tx_type,json=txType,proto3" json:"tx_type,omitempty"`
	To        []byte   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Value     []byte   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp int64    `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Nonce     uint64   `protobuf:"varint,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ChainId   uint32   `protobuf:"varint,7,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Payload   []byte   `protobuf:"bytes,10,opt,name=payload,proto3" json:"payload,omitempty"`
	Alg       uint32   `protobuf:"varint,21,opt,name=alg,proto3" json:"alg,omitempty"`
	Sign      []byte   `protobuf:"bytes,22,opt,name=sign,proto3" json:"sign,omitempty"`
	PayerSign []byte   `protobuf:"bytes,23,opt,name=payerSign,proto3" json:"payerSign,omitempty"`
	Receipt   *Receipt `protobuf:"bytes,30,opt,name=receipt" json:"receipt,omitempty"`
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptorBlock, []int{4} }

func (m *Transaction) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Transaction) GetTxType() string {
	if m != nil {
		return m.TxType
	}
	return ""
}

func (m *Transaction) GetTo() []byte {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Transaction) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Transaction) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Transaction) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Transaction) GetChainId() uint32 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *Transaction) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Transaction) GetAlg() uint32 {
	if m != nil {
		return m.Alg
	}
	return 0
}

func (m *Transaction) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

func (m *Transaction) GetPayerSign() []byte {
	if m != nil {
		return m.PayerSign
	}
	return nil
}

func (m *Transaction) GetReceipt() *Receipt {
	if m != nil {
		return m.Receipt
	}
	return nil
}

type Receipt struct {
	Executed bool   `protobuf:"varint,1,opt,name=executed,proto3" json:"executed,omitempty"`
	CpuUsage []byte `protobuf:"bytes,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	NetUsage []byte `protobuf:"bytes,3,opt,name=net_usage,json=netUsage,proto3" json:"net_usage,omitempty"`
	Error    []byte `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
}

func (m *Receipt) Reset()                    { *m = Receipt{} }
func (m *Receipt) String() string            { return proto.CompactTextString(m) }
func (*Receipt) ProtoMessage()               {}
func (*Receipt) Descriptor() ([]byte, []int) { return fileDescriptorBlock, []int{5} }

func (m *Receipt) GetExecuted() bool {
	if m != nil {
		return m.Executed
	}
	return false
}

func (m *Receipt) GetCpuUsage() []byte {
	if m != nil {
		return m.CpuUsage
	}
	return nil
}

func (m *Receipt) GetNetUsage() []byte {
	if m != nil {
		return m.NetUsage
	}
	return nil
}

func (m *Receipt) GetError() []byte {
	if m != nil {
		return m.Error
	}
	return nil
}

type TransactionHashTarget struct {
	TxType    string `protobuf:"bytes,1,opt,name=tx_type,json=txType,proto3" json:"tx_type,omitempty"`
	To        []byte `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Value     []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp int64  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Nonce     uint64 `protobuf:"varint,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ChainId   uint32 `protobuf:"varint,6,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Payload   []byte `protobuf:"bytes,10,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *TransactionHashTarget) Reset()                    { *m = TransactionHashTarget{} }
func (m *TransactionHashTarget) String() string            { return proto.CompactTextString(m) }
func (*TransactionHashTarget) ProtoMessage()               {}
func (*TransactionHashTarget) Descriptor() ([]byte, []int) { return fileDescriptorBlock, []int{6} }

func (m *TransactionHashTarget) GetTxType() string {
	if m != nil {
		return m.TxType
	}
	return ""
}

func (m *TransactionHashTarget) GetTo() []byte {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *TransactionHashTarget) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *TransactionHashTarget) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *TransactionHashTarget) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *TransactionHashTarget) GetChainId() uint32 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *TransactionHashTarget) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type DefaultPayload struct {
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (m *DefaultPayload) Reset()                    { *m = DefaultPayload{} }
func (m *DefaultPayload) String() string            { return proto.CompactTextString(m) }
func (*DefaultPayload) ProtoMessage()               {}
func (*DefaultPayload) Descriptor() ([]byte, []int) { return fileDescriptorBlock, []int{7} }

func (m *DefaultPayload) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type VotePayload struct {
	Candidates [][]byte `protobuf:"bytes,1,rep,name=candidates" json:"candidates,omitempty"`
}

func (m *VotePayload) Reset()                    { *m = VotePayload{} }
func (m *VotePayload) String() string            { return proto.CompactTextString(m) }
func (*VotePayload) ProtoMessage()               {}
func (*VotePayload) Descriptor() ([]byte, []int) { return fileDescriptorBlock, []int{8} }

func (m *VotePayload) GetCandidates() [][]byte {
	if m != nil {
		return m.Candidates
	}
	return nil
}

type AddCertificationPayload struct {
	IssueTime      int64  `protobuf:"varint,1,opt,name=issue_time,json=issueTime,proto3" json:"issue_time,omitempty"`
	ExpirationTime int64  `protobuf:"varint,2,opt,name=expiration_time,json=expirationTime,proto3" json:"expiration_time,omitempty"`
	Hash           []byte `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *AddCertificationPayload) Reset()                    { *m = AddCertificationPayload{} }
func (m *AddCertificationPayload) String() string            { return proto.CompactTextString(m) }
func (*AddCertificationPayload) ProtoMessage()               {}
func (*AddCertificationPayload) Descriptor() ([]byte, []int) { return fileDescriptorBlock, []int{9} }

func (m *AddCertificationPayload) GetIssueTime() int64 {
	if m != nil {
		return m.IssueTime
	}
	return 0
}

func (m *AddCertificationPayload) GetExpirationTime() int64 {
	if m != nil {
		return m.ExpirationTime
	}
	return 0
}

func (m *AddCertificationPayload) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type RevokeCertificationPayload struct {
	Hash []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *RevokeCertificationPayload) Reset()                    { *m = RevokeCertificationPayload{} }
func (m *RevokeCertificationPayload) String() string            { return proto.CompactTextString(m) }
func (*RevokeCertificationPayload) ProtoMessage()               {}
func (*RevokeCertificationPayload) Descriptor() ([]byte, []int) { return fileDescriptorBlock, []int{10} }

func (m *RevokeCertificationPayload) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type AddRecordPayload struct {
	Hash []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *AddRecordPayload) Reset()                    { *m = AddRecordPayload{} }
func (m *AddRecordPayload) String() string            { return proto.CompactTextString(m) }
func (*AddRecordPayload) ProtoMessage()               {}
func (*AddRecordPayload) Descriptor() ([]byte, []int) { return fileDescriptorBlock, []int{11} }

func (m *AddRecordPayload) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type RegisterAliasPayload struct {
	AliasName string `protobuf:"bytes,1,opt,name=alias_name,json=aliasName,proto3" json:"alias_name,omitempty"`
}

func (m *RegisterAliasPayload) Reset()                    { *m = RegisterAliasPayload{} }
func (m *RegisterAliasPayload) String() string            { return proto.CompactTextString(m) }
func (*RegisterAliasPayload) ProtoMessage()               {}
func (*RegisterAliasPayload) Descriptor() ([]byte, []int) { return fileDescriptorBlock, []int{12} }

func (m *RegisterAliasPayload) GetAliasName() string {
	if m != nil {
		return m.AliasName
	}
	return ""
}

func init() {
	proto.RegisterType((*BlockHeader)(nil), "corepb.BlockHeader")
	proto.RegisterType((*Block)(nil), "corepb.Block")
	proto.RegisterType((*DownloadParentBlock)(nil), "corepb.DownloadParentBlock")
	proto.RegisterType((*BlockHashTarget)(nil), "corepb.BlockHashTarget")
	proto.RegisterType((*Transaction)(nil), "corepb.Transaction")
	proto.RegisterType((*Receipt)(nil), "corepb.Receipt")
	proto.RegisterType((*TransactionHashTarget)(nil), "corepb.TransactionHashTarget")
	proto.RegisterType((*DefaultPayload)(nil), "corepb.DefaultPayload")
	proto.RegisterType((*VotePayload)(nil), "corepb.VotePayload")
	proto.RegisterType((*AddCertificationPayload)(nil), "corepb.AddCertificationPayload")
	proto.RegisterType((*RevokeCertificationPayload)(nil), "corepb.RevokeCertificationPayload")
	proto.RegisterType((*AddRecordPayload)(nil), "corepb.AddRecordPayload")
	proto.RegisterType((*RegisterAliasPayload)(nil), "corepb.RegisterAliasPayload")
}

func init() { proto.RegisterFile("block.proto", fileDescriptorBlock) }

var fileDescriptorBlock = []byte{
	// 821 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x95, 0xcf, 0x6e, 0xdb, 0x46,
	0x10, 0xc6, 0x41, 0x52, 0x7f, 0xac, 0xa1, 0x63, 0x07, 0x8c, 0x6c, 0x6f, 0xd3, 0xd4, 0x51, 0x89,
	0xa2, 0x75, 0x5b, 0xd4, 0x28, 0x52, 0x14, 0x3d, 0xf5, 0xe0, 0x36, 0x87, 0xf4, 0x52, 0x04, 0x1b,
	0xb7, 0x57, 0x61, 0xbd, 0x1c, 0x4b, 0x8b, 0x48, 0xdc, 0xc5, 0xee, 0x32, 0x91, 0x1e, 0xa0, 0xef,
	0xd4, 0x5b, 0xfb, 0x4a, 0x7d, 0x83, 0x62, 0x77, 0xc9, 0x90, 0x92, 0x65, 0xd5, 0xe8, 0x8d, 0xf3,
	0xcd, 0x8c, 0xc8, 0xf9, 0x7e, 0x33, 0x10, 0xa4, 0x37, 0x0b, 0xc9, 0xdf, 0x5e, 0x2a, 0x2d, 0xad,
	0xcc, 0x06, 0x5c, 0x6a, 0x54, 0x37, 0xf9, 0xdf, 0x09, 0xa4, 0x3f, 0x39, 0xfd, 0x15, 0xb2, 0x02,
	0x75, 0x96, 0x41, 0x6f, 0xce, 0xcc, 0x9c, 0x44, 0x93, 0xe8, 0xe2, 0x90, 0xfa, 0xe7, 0xec, 0x39,
	0xa4, 0x8a, 0x69, 0x2c, 0xed, 0xd4, 0xa7, 0x62, 0x9f, 0x82, 0x20, 0xbd, 0x72, 0x05, 0x4f, 0xe1,
	0x80, 0x4b, 0x51, 0xde, 0x30, 0x83, 0x24, 0xf1, 0xd9, 0x0f, 0x71, 0x76, 0x0a, 0x03, 0x8d, 0xef,
	0x99, 0x2e, 0x48, 0xcf, 0x67, 0xea, 0xc8, 0xe9, 0xa6, 0x52, 0x6a, 0xb1, 0x26, 0xfd, 0xa0, 0x87,
	0x28, 0x7b, 0x06, 0x23, 0x2b, 0x96, 0x68, 0x2c, 0x5b, 0x2a, 0x32, 0x98, 0x44, 0x17, 0x09, 0x6d,
	0x85, 0xec, 0x23, 0x38, 0xe0, 0x73, 0x26, 0xca, 0xa9, 0x28, 0xc8, 0x70, 0x12, 0x5d, 0x3c, 0xa2,
	0x43, 0x1f, 0xff, 0x52, 0x64, 0x8f, 0x21, 0x61, 0x8b, 0x19, 0x49, 0xbd, 0xea, 0x1e, 0xdd, 0x2c,
	0x46, 0xcc, 0x4a, 0x72, 0x18, 0x66, 0x71, 0xcf, 0xd9, 0x67, 0x70, 0xc4, 0x38, 0x9f, 0x1a, 0xcb,
	0x2c, 0x4e, 0xb5, 0x94, 0x96, 0x9c, 0xf8, 0xec, 0x21, 0xe3, 0xfc, 0x8d, 0x13, 0xa9, 0x94, 0x36,
	0xcb, 0xe1, 0x91, 0x5d, 0x75, 0x8b, 0x4e, 0x7d, 0x51, 0x6a, 0x57, 0x6d, 0xcd, 0xc7, 0x30, 0x2a,
	0x94, 0x34, 0x21, 0x7f, 0x16, 0xa6, 0x76, 0x82, 0x4f, 0x9e, 0xc1, 0x90, 0xab, 0x6a, 0xaa, 0xf1,
	0x96, 0x9c, 0x87, 0xf1, 0xb8, 0xaa, 0x28, 0xde, 0xba, 0x2e, 0x97, 0xa8, 0x0c, 0x9b, 0x21, 0x79,
	0x5e, 0x7b, 0xa5, 0xaa, 0xdf, 0x5c, 0xec, 0xba, 0x4a, 0xb4, 0xbe, 0x6b, 0x12, 0xba, 0x4a, 0xb4,
	0x75, 0x97, 0x4b, 0x84, 0xae, 0x4f, 0x43, 0x57, 0x89, 0xd6, 0x77, 0xe5, 0x7f, 0x44, 0xd0, 0xf7,
	0x08, 0xb3, 0xaf, 0x61, 0x30, 0xf7, 0x18, 0x3d, 0xbe, 0xf4, 0xc5, 0x93, 0xcb, 0x40, 0xf9, 0xb2,
	0x43, 0x98, 0xd6, 0x25, 0xd9, 0x0f, 0x70, 0x68, 0x35, 0x2b, 0x0d, 0xe3, 0x56, 0xc8, 0xd2, 0x90,
	0x78, 0x92, 0x74, 0x5b, 0xae, 0xdb, 0x1c, 0xdd, 0x28, 0x74, 0xe4, 0xe6, 0x28, 0x66, 0x73, 0xeb,
	0x59, 0xf7, 0x68, 0x1d, 0xe5, 0x3f, 0xc2, 0x93, 0x97, 0xf2, 0x7d, 0xb9, 0x90, 0xac, 0x78, 0xed,
	0x77, 0x23, 0x7c, 0xd4, 0xae, 0x8d, 0x6a, 0xc8, 0xc4, 0x2d, 0x99, 0xfc, 0x9f, 0x18, 0x8e, 0xc3,
	0x77, 0x32, 0x33, 0xbf, 0x66, 0x7a, 0x86, 0x76, 0x7b, 0xf3, 0xa2, 0xbd, 0x9b, 0x17, 0x6f, 0x6d,
	0xde, 0x5d, 0xd4, 0xc9, 0x43, 0x50, 0xf7, 0xfe, 0x03, 0x75, 0x7f, 0x0b, 0xf5, 0xff, 0x5e, 0xd8,
	0xf6, 0x32, 0x0e, 0xee, 0xb9, 0x8c, 0xd1, 0xc6, 0x65, 0x6c, 0xac, 0xce, 0x78, 0x6b, 0x75, 0x36,
	0x36, 0xe4, 0x64, 0x73, 0x43, 0xdc, 0x5e, 0xd9, 0x55, 0xb0, 0xf0, 0x7c, 0x92, 0xb8, 0x9f, 0xb4,
	0x2b, 0x67, 0x5f, 0xfe, 0x67, 0x0c, 0x69, 0x07, 0xf4, 0x4e, 0x56, 0xa1, 0xd9, 0xae, 0x55, 0x70,
	0x78, 0xe4, 0x9a, 0xaf, 0xd7, 0x0a, 0xb3, 0x23, 0x88, 0xad, 0xac, 0x3d, 0x8d, 0xad, 0xcc, 0xc6,
	0xd0, 0x7f, 0xc7, 0x16, 0x15, 0xd6, 0x0e, 0x86, 0x60, 0xd3, 0x9e, 0xfe, 0xb6, 0x3d, 0x63, 0xe8,
	0x97, 0xb2, 0xe4, 0xe8, 0x8d, 0xeb, 0xd1, 0x10, 0xec, 0x33, 0x8d, 0xc0, 0x50, 0xb1, 0xb5, 0xdb,
	0x31, 0x02, 0xfe, 0x35, 0x4d, 0xd8, 0xdc, 0xff, 0xc9, 0xdd, 0xfb, 0x3f, 0xed, 0xdc, 0xff, 0x33,
	0x18, 0x29, 0xb6, 0x46, 0xfd, 0xc6, 0x25, 0xc2, 0xd5, 0xb6, 0x42, 0xf6, 0x25, 0x0c, 0x35, 0x72,
	0x14, 0xca, 0xfa, 0xb3, 0x4d, 0x5f, 0x1c, 0x37, 0xe7, 0x40, 0x83, 0x4c, 0x9b, 0x7c, 0x5e, 0xc1,
	0xb0, 0xd6, 0xdc, 0x12, 0xe2, 0x0a, 0x79, 0x65, 0xb1, 0xf0, 0xce, 0x1d, 0xd0, 0x0f, 0xf1, 0x26,
	0xb4, 0x78, 0x1f, 0xb4, 0x64, 0x0b, 0xda, 0x18, 0xfa, 0xa8, 0xb5, 0xd4, 0x8d, 0x9d, 0x3e, 0xc8,
	0xff, 0x8a, 0xe0, 0xa4, 0x43, 0xac, 0x73, 0x2b, 0x1d, 0x4e, 0xd1, 0x0e, 0x4e, 0xf1, 0x5d, 0x4e,
	0xc9, 0xbd, 0x9c, 0x7a, 0xf7, 0x72, 0xea, 0xdf, 0xc7, 0x69, 0xf0, 0x40, 0x4e, 0xf9, 0x57, 0x70,
	0xf4, 0x12, 0x6f, 0x59, 0xb5, 0xb0, 0xaf, 0x6b, 0x72, 0x04, 0x86, 0x4b, 0x34, 0xde, 0x84, 0xf0,
	0xe5, 0x4d, 0x98, 0x7f, 0x03, 0xe9, 0xef, 0xd2, 0x62, 0x53, 0x78, 0x0e, 0xc0, 0x59, 0x59, 0x88,
	0x82, 0x59, 0x34, 0x24, 0xf2, 0xab, 0xdc, 0x51, 0xf2, 0x0a, 0xce, 0xae, 0x8a, 0xe2, 0x67, 0xd4,
	0x56, 0xdc, 0x0a, 0xce, 0x9c, 0x41, 0x4d, 0xeb, 0x27, 0x00, 0xc2, 0x98, 0x0a, 0xa7, 0x6e, 0x26,
	0xff, 0x9a, 0x84, 0x8e, 0xbc, 0x72, 0x2d, 0x96, 0x98, 0x7d, 0x01, 0xc7, 0xb8, 0x52, 0x42, 0xfb,
	0x9e, 0x50, 0x13, 0xfb, 0x9a, 0xa3, 0x56, 0xf6, 0x85, 0xcd, 0x85, 0x24, 0xed, 0x85, 0xe4, 0xdf,
	0xc2, 0x53, 0x8a, 0xef, 0xe4, 0x5b, 0xdc, 0xf9, 0xe6, 0x1d, 0x37, 0x95, 0x7f, 0x0e, 0x8f, 0xaf,
	0x8a, 0x82, 0x22, 0x97, 0xba, 0xd8, 0x57, 0xf7, 0x3d, 0x8c, 0x29, 0xce, 0x84, 0xb1, 0xa8, 0xaf,
	0x16, 0x82, 0x99, 0xce, 0x34, 0xcc, 0xc5, 0xd3, 0x92, 0x2d, 0x1b, 0xd3, 0x46, 0x5e, 0xf9, 0x95,
	0x2d, 0xf1, 0x66, 0xe0, 0xff, 0xe3, 0xbf, 0xfb, 0x37, 0x00, 0x00, 0xff, 0xff, 0x93, 0x98, 0xfa,
	0xc4, 0xf2, 0x07, 0x00, 0x00,
}
