// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: consensus.proto

/*
Package dpospb is a generated protocol buffer package.

It is generated from these files:
	consensus.proto

It has these top-level messages:
	ConsensusState
*/
package dpospb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ConsensusState struct {
	DynastyRoot []byte `protobuf:"bytes,1,opt,name=dynasty_root,json=dynastyRoot,proto3" json:"dynasty_root,omitempty"`
	DynastySize int64  `protobuf:"varint,2,opt,name=dynasty_size,json=dynastySize,proto3" json:"dynasty_size,omitempty"`
	Proposer    []byte `protobuf:"bytes,3,opt,name=proposer,proto3" json:"proposer,omitempty"`
	Timestamp   int64  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	StartTime   int64  `protobuf:"varint,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
}

func (m *ConsensusState) Reset()                    { *m = ConsensusState{} }
func (m *ConsensusState) String() string            { return proto.CompactTextString(m) }
func (*ConsensusState) ProtoMessage()               {}
func (*ConsensusState) Descriptor() ([]byte, []int) { return fileDescriptorConsensus, []int{0} }

func (m *ConsensusState) GetDynastyRoot() []byte {
	if m != nil {
		return m.DynastyRoot
	}
	return nil
}

func (m *ConsensusState) GetDynastySize() int64 {
	if m != nil {
		return m.DynastySize
	}
	return 0
}

func (m *ConsensusState) GetProposer() []byte {
	if m != nil {
		return m.Proposer
	}
	return nil
}

func (m *ConsensusState) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ConsensusState) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func init() {
	proto.RegisterType((*ConsensusState)(nil), "dpospb.ConsensusState")
}

func init() { proto.RegisterFile("consensus.proto", fileDescriptorConsensus) }

var fileDescriptorConsensus = []byte{
	// 173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xcf, 0x31, 0xae, 0xc2, 0x30,
	0x0c, 0x06, 0x60, 0xe5, 0xf5, 0x51, 0x81, 0xa9, 0x40, 0xca, 0x14, 0x21, 0x90, 0x0a, 0x53, 0x27,
	0x16, 0x8e, 0xc0, 0x0d, 0x5a, 0xf6, 0x2a, 0xa5, 0x1e, 0x32, 0xb4, 0x8e, 0x62, 0x33, 0xb4, 0x97,
	0xe2, 0x8a, 0x88, 0x00, 0x85, 0xd1, 0xdf, 0xff, 0xdb, 0x92, 0x61, 0x7d, 0xa5, 0x9e, 0xb1, 0xe7,
	0x1b, 0x1f, 0x7d, 0x20, 0x21, 0x9d, 0xb6, 0x9e, 0xd8, 0x37, 0x87, 0xbb, 0x82, 0xd5, 0xf9, 0x93,
	0x55, 0x62, 0x05, 0xf5, 0x1e, 0xb2, 0x76, 0xe8, 0x2d, 0xcb, 0x50, 0x07, 0x22, 0x31, 0x2a, 0x57,
	0x45, 0x56, 0x2e, 0xdf, 0x56, 0x12, 0xc9, 0x6f, 0x85, 0xdd, 0x88, 0xe6, 0x2f, 0x57, 0x45, 0x32,
	0x55, 0x2a, 0x37, 0xa2, 0xde, 0xc0, 0xdc, 0x07, 0xf2, 0xc4, 0x18, 0x4c, 0x12, 0x2f, 0x4c, 0xb3,
	0xde, 0xc2, 0x42, 0x5c, 0x87, 0x2c, 0xb6, 0xf3, 0xe6, 0x3f, 0xee, 0x7e, 0x41, 0xef, 0x00, 0x58,
	0x6c, 0x90, 0xfa, 0x49, 0x66, 0xf6, 0x8a, 0xa3, 0x5c, 0x5c, 0x87, 0x4d, 0x1a, 0x1f, 0x38, 0x3d,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x2d, 0x80, 0xcf, 0xf9, 0xd3, 0x00, 0x00, 0x00,
}
