// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: message_test.proto

/*
Package netpb is a generated protocol buffer package.

It is generated from these files:
	message_test.proto

It has these top-level messages:
	TestMsg
*/
package netpb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type TestMsg struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *TestMsg) Reset()                    { *m = TestMsg{} }
func (m *TestMsg) String() string            { return proto.CompactTextString(m) }
func (*TestMsg) ProtoMessage()               {}
func (*TestMsg) Descriptor() ([]byte, []int) { return fileDescriptorMessageTest, []int{0} }

func (m *TestMsg) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*TestMsg)(nil), "netpb.TestMsg")
}

func init() { proto.RegisterFile("message_test.proto", fileDescriptorMessageTest) }

var fileDescriptorMessageTest = []byte{
	// 84 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xca, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x8d, 0x2f, 0x49, 0x2d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0xcd, 0x4b, 0x2d, 0x29, 0x48, 0x52, 0x92, 0xe5, 0x62, 0x0f, 0x49, 0x2d, 0x2e, 0xf1, 0x2d, 0x4e,
	0x17, 0x12, 0xe2, 0x62, 0x49, 0x49, 0x2c, 0x49, 0x94, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x09, 0x02,
	0xb3, 0x93, 0xd8, 0xc0, 0x8a, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x06, 0xf1, 0xbc, 0xe3,
	0x42, 0x00, 0x00, 0x00,
}
